version: '3.9'
services:
  db_bp:
    container_name: db_bp
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booking_platform
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: BookingPlatformAPI
    ports:
      - "8080:8080"
    depends_on:
      - db_bp
    build:
      dockerfile: .\Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_bp/booking_platform
volumes:
  data: